FROM arm64v8/ubuntu:24.04

RUN apt-get update && apt-get install -y libsqlite3-dev sqlite3 libicu-dev gcc wget xz-utils && rm -rf /var/lib/apt/lists/*

RUN wget -q https://ziglang.org/download/0.16.0/zig-aarch64-linux-0.16.0.tar.xz && \
    tar xf zig-aarch64-linux-0.16.0.tar.xz -C /usr/local && \
    ln -s /usr/local/zig-aarch64-linux-0.16.0/zig /usr/local/bin/zig && \
    rm zig-aarch64-linux-0.16.0.tar.xz

WORKDIR /workspace
