FROM almalinux:10

RUN dnf install -y epel-release && dnf install -y sqlite-devel libicu-devel gcc wget xz && dnf clean all

RUN ARCH=$(uname -m) && \
    for VER in 0.16.0 0.17.0; do \
        wget -q "https://ziglang.org/download/${VER}/zig-${ARCH}-linux-${VER}.tar.xz" && \
        tar xf "zig-${ARCH}-linux-${VER}.tar.xz" -C /usr/local && \
        ln -s "/usr/local/zig-${ARCH}-linux-${VER}/zig" "/usr/local/bin/zig-${VER}" && \
        rm "zig-${ARCH}-linux-${VER}.tar.xz"; \
    done && \
    ln -s /usr/local/bin/zig-0.16.0 /usr/local/bin/zig

WORKDIR /workspace
